routes/web.php
<?php

use App\Http\Controllers\DosenController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StokController;
use App\Http\Controllers\filmController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::resource('siswa', \App\Http\Controllers\SiswaController::class);
Route::get('cari', [\App\Http\Controllers\SiswaController::class, 'cari'])->name('siswa.cari');
Route::resource('pegawais', \App\Http\Controllers\pegawaiController::class);
Route::get('search', [\App\Http\Controllers\pegawaiController::class, 'search'])->name('pegawais.search');
Route::resource('films', filmController::class);
Route::get('cri', [filmController::class, 'cri'])->name('films.cri');
Route::resource('stok', StokController::class);
Route::resource('peserta', \App\Http\Controllers\PesertaController::class);
Route::resource('user', \App\Http\Controllers\UserController::class);
// Route::get('/dashboard', function () {return view('welcome');})->name('dashboard');
Route::resource('dosen', DosenController::class);
Route::resource('role',\App\Http\Controllers\RoleController::class);
Route::resource('permission',\App\Http\Controllers\PermissionController::class);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('auth/google',[\App\Http\Controllers\GoogleController::class,'redirectToGoogle'])->name('google.login');
Route::get('auth/google/callback',[\App\Http\Controllers\GoogleController::class,'handleGoogleCallback'])->name('google.callback');

Route::get('dashboard',[\App\Http\Controllers\DashboardController::class,'index'])->name('dashboard');

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    protected $table = 'siswa';

    protected $fillable = ['nim','nama','prodi'];
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */

    function __construct()
    {
        $this->middleware('role_or_permission:Siswa access|Siswa create|Siswa edit|Siswa delete', ['only' => ['index','show']]);
        $this->middleware('role_or_permission:Siswa create', ['only' => ['create','store']]);
        $this->middleware('role_or_permission:Siswa edit', ['only' => ['edit','update']]);
        $this->middleware('role_or_permission:Siswa delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        $datasiswa = DB::table('siswa')->paginate(5);
        return view('siswa.index',['siswa' => $datasiswa]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('siswa.form_tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        Siswa::create([
            'nim' => $request->nim,
            'nama' => $request->nama,
            'prodi' => $request->prodi
        ]);

        return redirect()->route('siswa.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($id)
    {
        $siswa = Siswa::where('id',$id)->first();
        return view('siswa.profil_siswa',['siswa' => $siswa]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $datasiswa = Siswa::find($id);
        return view('siswa.form_ubah', ['siswa'=>$datasiswa]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $siswa= Siswa::find($id);
        $siswa->nim = $request->nim;
        $siswa->nama = $request->nama;
        $siswa->prodi = $request->prodi;
        $siswa->save();

        return redirect()->route('siswa.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    // public function destroy($id)
    // {
    //     $siswa = Siswa::find($id);
    //     $siswa->delete();

    //     return redirect()->route('siswa.index');
    // }
    public function destroy(Siswa $siswa)
    {
        $siswa->delete();

        return redirect()->route('siswa.index');
    }
    public function cari(Request $request)
        {
             // menangkap data pencarian
             $cari = $request->cari;

             // mengambil data dari table guru sesuai pencarian data
             $datasiswa = DB::table('siswa')
             ->where('nama','like',"%".$cari."%")
             ->paginate(5);

             // mengirim data pegawai ke view index
             return view('siswa.index',['siswa' => $datasiswa]);

        }
}

resources/views/siswa/form_tambah.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>TAMBAH DATA MAHASISWA</h2>
            </div>
            <div class="card-body">
                <form action="{{route('siswa.store')}}" method="post">
                    @csrf
                    <div class="container mt-4">
                        <div class="form-floating mb-3">
                            <label for="nim">NIM</label>
                            <input type="text" class="form-control" id="nim" name="nim">
                        </div>
                        <div class="form-floating mb-3">
                            <label for="nama">Nama</label>
                            <input type="text" class="form-control" id="nama" name="nama">
                        </div>
                        <div class="form-group">
                            <label for="exampleSelectRounded0">Program Studi</label>
                            <select class="custom-select rounded-0" id="exampleSelectRounded0" name="prodi">
                                <option value="Teknik Informasi">Teknik Infromatika</option>
                                <option value="Sistem Informasi">Sistem Infromasi</option>
                            </select>
                        </div>
                        <button class="btn btn-primary mr-1" name="submit" type="submit">Submit</button>
                        <a href="{{route('siswa.index')}}" class="btn btn-danger">Cancel</a>
                    </div>
            </div>
            </form>
            </div>
        </div>
    </div>


@endsection

resources/views/siswa/form_ubah.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>PENDATAAN MAHASISWA ILMU KOMPUTER</h2>
            </div>
            <div class="card-body">
                <form action="{{route('siswa.update', $siswa->id)}}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="container mt-4">
                        <div class="form-floating mb-3">
                            <label for="nim">NIM</label>
                            <input type="text" class="form-control" id="nim" name="nim" required value="{{$siswa->nim}}" >
                        </div>
                        <div class="form-floating mb-3">
                            <label for="nama">Nama</label>
                            <input type="text" class="form-control" id="nama" name="nama" required value="{{$siswa->nama}}">
                        </div>
                        <div class="form-group">
                            <label for="exampleSelectRounded0">Program Studi</label>
                            <select class="custom-select rounded-0" id="exampleSelectRounded0" name="prodi">
                                <option selected>{{$siswa->prodi}}</option>
                                <option value="Teknik Informasi">Teknik Infromatika</option>
                                <option value="Sistem Informasi">Sistem Infromasi</option>
                            </select>
                        </div>
                        <button class="btn btn-primary mr-1" name="submit" type="submit">Submit</button>
                        <a href="{{route('siswa.index')}}" class="btn btn-danger">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>



@endsection

resources/views/siswa/index.blade.php
@extends('layouts.app')

@section('content')
<!-- page content -->
<div class="container">
<div class="card" >
    <div class="card-header">
        <h2>Data Mahasiswa Ilmu Komputer</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-8">
                @can('Siswa create')
                <a href="{{route('siswa.create')}}" class="btn btn-primary mb-2"> Tambah</a>
                @endcan
            </div>
            <div class="col-md-4">
                <form action="{{route('siswa.cari')}}" method="GET">
                    <input class="form-control-sm" type="text" name="cari" placeholder="Cari Siswa ..">
                    <input class="btn btn-dark btm-sm" type="submit" value="CARI">
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>NIM</th>
                    <th>Nama Mahasiswa</th>
                    <th>Program Studi</th>
                    <th>Aksi</th>
                </tr>
                @can('Siswa access')
                @foreach($siswa as $s)
                <tr>
                    <td>{{$s->nim}}</td>
                    <td>{{$s->nama}}</td>
                    <td>{{$s->prodi}}</td>
                    <td>
                        <form action="{{route ('siswa.destroy', $s->id)  }}" method="POST">
                            <a href="{{ route ('siswa.show', $s->id) }}" class="btn btn-round btn-primary" > Tampilkan </a>
                            @can('Siswa edit')
                            <a href="{{route('siswa.edit', $s->id)}}" class="btn btn-success">Edit </a>
                            @endcan
                            @csrf
                            @method('DELETE')
                            @can('Siswa delete')
                            <button type="submit" class="btn btn-danger">Delete</button>
                            @endcan
                        </form>
                    </td>
                </tr>
                @endforeach
                @endcan
            </table>

            <br/>
            <div class="col mb-2">
                <div class="row-4">
                    Halaman : {{ $siswa->currentPage() }}
                </div>
                <div class="row-4">
                    Jumlah Data : {{ $siswa->total() }}
                </div>
                <div class="row-4">
                    Data Per Halaman : {{ $siswa->perPage() }}
                </div>
                {{ $siswa->links() }}
            </div>
    </div>
</div>
</div>
@endsection

resources/views/siswa/profil_siswa.blade.php
@extends('layouts.app')

@section('content')
    <div class="container d-flex justify-conten-center">
        <div class="card w-50">
            <div class="card-header">
                <h3>Profil Siswa</h3>
            </div>
            <div class="card-body">
                <a href="{{route ('siswa.index')}}">Kembali</a>
                <div class="card-body">
                    <div class="row ml-4">
                        <h4 class="col-6">Nama</h4>
                        <h4 class="col-6" >: {{$siswa->nama}}</h4>
                    </div>
                    <div class="row ml-4">
                        <h4 class="col-6">NIM</h4>
                        <h4 class="col-6" >: {{$siswa->nim}}</h4>
                    </div>
                    <div class="row ml-4">
                        <h4 class="col-6">Prodi</h4>
                        <h4 class="col-6">: {{$siswa->prodi}}</h4>
                    </div>
                </div>
            </div>
        </div>


@endsection