routes/web.php
<?php

use App\Http\Controllers\DosenController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StokController;
use App\Http\Controllers\filmController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::resource('siswa', \App\Http\Controllers\SiswaController::class);
Route::get('cari', [\App\Http\Controllers\SiswaController::class, 'cari'])->name('siswa.cari');
Route::resource('pegawais', \App\Http\Controllers\pegawaiController::class);
Route::get('search', [\App\Http\Controllers\pegawaiController::class, 'search'])->name('pegawais.search');
Route::resource('films', filmController::class);
Route::get('cri', [filmController::class, 'cri'])->name('films.cri');
Route::resource('stok', StokController::class);
Route::resource('peserta', \App\Http\Controllers\PesertaController::class);
Route::resource('user', \App\Http\Controllers\UserController::class);
// Route::get('/dashboard', function () {return view('welcome');})->name('dashboard');
Route::resource('dosen', DosenController::class);
Route::resource('role',\App\Http\Controllers\RoleController::class);
Route::resource('permission',\App\Http\Controllers\PermissionController::class);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('auth/google',[\App\Http\Controllers\GoogleController::class,'redirectToGoogle'])->name('google.login');
Route::get('auth/google/callback',[\App\Http\Controllers\GoogleController::class,'handleGoogleCallback'])->name('google.callback');

Route::get('dashboard',[\App\Http\Controllers\DashboardController::class,'index'])->name('dashboard');

app/Models/pegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class pegawai extends Model
{
    use HasFactory;
    protected $fillable = [
        'nama', 'jabatan','nik', 'tgl_lahir'
    ];
}

app/Http/Controllers/pegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Models\pegawai;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class pegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    function __construct()
    {
        $this->middleware('role_or_permission:Pegawai access|Pegawai create|Pegawai edit|Pegawai delete', ['only' => ['index','show']]);
        $this->middleware('role_or_permission:Pegawai create', ['only' => ['create','store']]);
        $this->middleware('role_or_permission:Pegawai edit', ['only' => ['edit','update']]);
        $this->middleware('role_or_permission:Pegawai delete', ['only' => ['destroy']]);
    }
    public function index()
    {
        $data = DB::table('pegawais')->paginate(5);
        return view('pegawais.index',compact('data'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pegawais.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'nik' => 'required',
            'tgl_lahir' => 'required',
            'jabatan' => 'required',
        ]);

        pegawai::create($request->all());

        return redirect()->route('pegawais.index')
            ->with('success','data berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function show(pegawai $pegawai)
    {
        return view('pegawais.show',compact('pegawai'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function edit(pegawai $pegawai)
    {
        return view('pegawais.edit',compact('pegawai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, pegawai $pegawai)
    {
        $request->validate([
            'nama' => 'required',
            'nik' => 'required',
            'tgl_lahir' => 'required',
            'jabatan' => 'required',
        ]);

        $pegawai->update($request->all());

        return redirect()->route('pegawais.index')
            ->with('success',' Data pegawai berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function destroy(pegawai $pegawai)
    {
        $pegawai->delete();

        return redirect()->route('pegawais.index')
            ->with('success','Data pegawai berhasil dihapus');
    }
    public function search(Request $request)
    {
        // menangkap data pencarian
        $search = $request->search;

        // mengambil data dari table guru sesuai pencarian data
        $data = DB::table('pegawais')
            ->where('nama','like',"%".$search."%")
            ->orWhere('nik','like',"%".$search."%")
            ->orWhere('jabatan','like',"%".$search."%")
            ->paginate();


        // mengirim data pegawai ke view index
        return view('pegawais.index',['data' => $data]);
    }
}

resources/views/pegawais/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="card-header">
                    <div class="pull-left">
                        <h2>Add</h2>
                    </div>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="card-body">
            <form action="{{ route('pegawais.store') }}" method="POST">
                @csrf
                
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Nama:</strong>
                            <input type="text" name="nama" class="form-control" placeholder="Masukkan Nama">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>NIK:</strong>
                            <input type="double" name="nik" class="form-control" placeholder="Masukkan NIK">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Tanggal Lahir:</strong>
                            <input type="date" name="tgl_lahir" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Jabatan:</strong>
                            <input type="text" name="jabatan" class="form-control" placeholder="Masukkan Jabatan">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a class="btn btn-danger" href="{{ route('pegawais.index') }}"> Back</a>
                    </div>
                    
            </form>
        </div>
        @endsection
    </div>
</div>
    

resources/views/pegawais/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Edit</h2>
                    </div>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="card-body">
            <form action="{{ route('pegawais.update',$pegawai->id) }}" method="POST">
                @csrf
                @method('PUT')
                
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Nama:</strong>
                            <input type="text" name="nama" value="{{ $pegawai->nama }}" class="form-control" placeholder="Nama">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>NIK:</strong>
                            <input type="double" name="nik" value="{{ $pegawai->nik }}" class="form-control" placeholder="NIK">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Tanggal Lahir:</strong>
                            <input type="date" name="tgl_lahir" value="{{ $pegawai->tgl_lahir }}" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Jabatan:</strong>
                            <input type="text" name="jabatan" value="{{ $pegawai->jabatan }}" class="form-control" placeholder="Jabatan">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a class="btn btn-primary" href="{{ route('pegawais.index') }}"> Back</a>
                    </div>
                </div>
            
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pegawais/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card"> 
        <div class="card-header">
            <h3>Daftar Data Pegawai</h3>
        </div>
        <div class="card-body">
            @can('User create')
            <div class="row">
                 <div class="col md -4">
                    <a class="btn btn-success" href="{{ route('pegawais.create') }}"> Create</a>
            </div>
            @endcan
            <div class="col-md-16" style="float:right;">
                <form action={{ route('pegawais.search') }} method="GET">
                    <label>
                        <input type="text" placeholder="Cari..." name="search" style="border-color:#0d6efd; height: 35px; ">
                    </label>
                    <button type="submit" class="btn btn-primary" >
                        <i class="fa fa-search mt-1"type="submit" ></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>            
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        
        <table class="table table-bordered">
            <tr align="center">
                <th>Nama</th>
                <th>NIK</th>
                <th>Tanggal Lahir</th>
                <th>Jabatan</th>
                <th width="250px">Action</th>
            </tr>
            @can('User access')
            @foreach ($data as $key => $value)
            <tr align="center">
                <td align="left">{{ $value->nama }}</td>
                <td>{{ $value->nik}}</td>
                <td>{{ $value->tgl_lahir }}</td>
                <td>{{ $value->jabatan }}</td>
                <td>
                    <form action="{{ route('pegawais.destroy',$value->id) }}" method="POST">
                        <a class="btn btn-primary" href="{{ route('pegawais.edit',$value->id) }}">Edit</a>
                        <a class="btn btn-info" href="{{ route('pegawais.show',$value->id) }}" style="margin-left: 1.3rem">Show</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" > Delete </button>
                        
                    </form>
                </td>
            </tr>
            @endforeach
            @endcan
        </table>
        
        <a class="btn btn-primary pull-right" style="margin-top:1rem; " href="{{ route('pegawais.index') }}"> Back</a>
        {{ $data->links() }}
    </div>
</div>
    
    @endsection
    

resources/views/pegawais/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="float-sm-left">
                        <h2> Show</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nama:</strong>
                        {{ $pegawai->nama }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nik:</strong>
                        {{ $pegawai->nik }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Tanggal Lahir:</strong>
                        {{ $pegawai->tgl_lahir }}
                    </div>
                </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Jabatan:</strong>
                    {{ $pegawai->jabatan }}
                </div>
                <div class="float-right">
                    <a class="btn btn-primary" href="{{ route('pegawais.index') }}"> Back</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection