routes/web.php
<?php

use App\Http\Controllers\DosenController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StokController;
use App\Http\Controllers\filmController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::resource('siswa', \App\Http\Controllers\SiswaController::class);
Route::get('cari', [\App\Http\Controllers\SiswaController::class, 'cari'])->name('siswa.cari');
Route::resource('pegawais', \App\Http\Controllers\pegawaiController::class);
Route::get('search', [\App\Http\Controllers\pegawaiController::class, 'search'])->name('pegawais.search');
Route::resource('films', filmController::class);
Route::get('cri', [filmController::class, 'cri'])->name('films.cri');
Route::resource('stok', StokController::class);
Route::resource('peserta', \App\Http\Controllers\PesertaController::class);
Route::resource('user', \App\Http\Controllers\UserController::class);
// Route::get('/dashboard', function () {return view('welcome');})->name('dashboard');
Route::resource('dosen', DosenController::class);
Route::resource('role',\App\Http\Controllers\RoleController::class);
Route::resource('permission',\App\Http\Controllers\PermissionController::class);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('auth/google',[\App\Http\Controllers\GoogleController::class,'redirectToGoogle'])->name('google.login');
Route::get('auth/google/callback',[\App\Http\Controllers\GoogleController::class,'handleGoogleCallback'])->name('google.callback');

Route::get('dashboard',[\App\Http\Controllers\DashboardController::class,'index'])->name('dashboard');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('role_or_permission:Role access|Role create|Role edit|Role delete', ['only' => ['index','show']]);
        $this->middleware('role_or_permission:Role create', ['only' => ['create','store']]);
        $this->middleware('role_or_permission:Role edit', ['only' => ['edit','update']]);
        $this->middleware('role_or_permission:Role delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $role= Role::get();
        return view('role.index',['roles'=>$role]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get();
        return view('role.form_tambah',['permissions'=>$permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['name'=>'required']);

        $role = Role::create(['name'=>$request->name]);

        $role->syncPermissions($request->permissions);

        return redirect()->route('role.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permission = Permission::get();
        $role->permissions;
        return view('role.form_ubah',['role'=>$role,'permissions' => $permission]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $role->update(['name'=>$request->name]);
        $role->syncPermissions($request->permissions);
        return redirect()->route('role.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        return redirect()->back()->withSuccess('Role deleted !!!');
    }
}

resources/views/role/form_tambah.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Ubah Data User</h3>
            </div>
            <div class="card-body">
                <a href="{{route ('role.index')}}" class="btn btn-primary mb-2">Kembali</a>
                <form action="{{route ('role.store')}}" method="post">
                    @csrf
                    <ul class="list-group">
                        <label  for="name">Nama</label>
                        <input class="mb-3" type="text" name="name" id="name" required>

                        <label for="permission">Permisiion</label>
                            @foreach($permissions as $permission)
                            <div class="flex flex-col justify-cente">
                                <div class="flex flex-col">
                                    <label class="inline-flex items-center ">
                                        <input type="checkbox" class="form-checkbox h-5 w-5 text-blue-600" name="permissions[]" id="permission" value="{{$permission->id}}"
                                        ><span class="ml-2 text-gray-700">{{ $permission->name }}</span>
                                    </label>
                                </div>
                            </div>
                        @endforeach
                    </ul>

                    <button class="btn btn-success" name="submit" type="submit">Submit</button>
                    <a href="{{route('role.index')}}" class="btn btn-danger">Cancel</a>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/role/form_ubah.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Ubah Data User</h3>
            </div>
            <div class="card-body">
                <a href="{{route ('role.index')}}" class="btn btn-primary mb-2">Kembali</a>
                <form action="{{route ('role.update', $role->id)}}" method="post">
                    @csrf
                    @method('PUT')
                    <ul class="list-group">
                        Nama <input type="text" name="name" required value="{{$role->name}}">
                        Permission @foreach($permissions as $permission)
                            <div class="flex flex-col justify-cente">
                                <div class="flex flex-col">
                                    <label class="inline-flex items-center mt-3">
                                        <input type="checkbox" class="form-checkbox h-5 w-5 text-blue-600" name="permissions[]" value="{{$permission->id}}"  @if(count($role->permissions->where('id',$permission->id)))
                                        checked
                                            @endif
                                        ><span class="ml-2 text-gray-700">{{ $permission->name }}</span>
                                    </label>
                                </div>
                            </div>
                        @endforeach
                    </ul>
                    <button class="btn btn-primary mt-3" name="submit" type="submit">Ubah Data</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/role/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Role Management</h3>
            </div>

            <div class="card-body">
                @can('Role create')
                    <div class="row mb-2">
                        <div class="col-md-3">
                            <a href="{{route('role.create')}}" class="btn btn-primary"> Tambah</a>
                        </div>
                    </div>
                @endcan
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Nama Role</th>
                        <th>Permission</th>
                        <th>Aksi</th>
                    </tr>

                    @can('User access')
                    @foreach($roles as $r)
                        <tr>
                            <td>{{ $r->name }}</td>
                            <td>
                                @foreach($r->permissions as $p)
                                    <button  class="btn btn btn-outline-dark btn-sm mt-2 ml-2 r-2" disabled data-bs-toggle="button">{{$p->name}}</button>
                                @endforeach
                            </td>
                            <td>
                                <ul class="nav">
                                    <form action="{{route ('role.destroy', $r->id)  }}" method="POST">
                                        @can('Role edit')
                                        <a href="{{ route ('role.edit', $r->id) }}" class="btn btn-primary mr-1 mb-1">Edit</a>
                                        @endcan
                                        @csrf
                                        @method('DELETE')
                                        @can('Role delete')
                                        <Button type="submit" class="btn btn-danger">Delete</Button>
                                        @endcan
                                    </form>
                                </ul>
                            </td>
                        </tr>
                    @endforeach
                    @endcan
                </table>
            </div>
        </div>
    </div>
@endsection