routes/web.php
<?php

use App\Http\Controllers\DosenController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StokController;
use App\Http\Controllers\filmController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::resource('siswa', \App\Http\Controllers\SiswaController::class);
Route::get('cari', [\App\Http\Controllers\SiswaController::class, 'cari'])->name('siswa.cari');
Route::resource('pegawais', \App\Http\Controllers\pegawaiController::class);
Route::get('search', [\App\Http\Controllers\pegawaiController::class, 'search'])->name('pegawais.search');
Route::resource('films', filmController::class);
Route::get('cri', [filmController::class, 'cri'])->name('films.cri');
Route::resource('stok', StokController::class);
Route::resource('peserta', \App\Http\Controllers\PesertaController::class);
Route::resource('user', \App\Http\Controllers\UserController::class);
// Route::get('/dashboard', function () {return view('welcome');})->name('dashboard');
Route::resource('dosen', DosenController::class);
Route::resource('role',\App\Http\Controllers\RoleController::class);
Route::resource('permission',\App\Http\Controllers\PermissionController::class);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('auth/google',[\App\Http\Controllers\GoogleController::class,'redirectToGoogle'])->name('google.login');
Route::get('auth/google/callback',[\App\Http\Controllers\GoogleController::class,'handleGoogleCallback'])->name('google.callback');

Route::get('dashboard',[\App\Http\Controllers\DashboardController::class,'index'])->name('dashboard');

app/Models/film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class film extends Model
{
    use HasFactory;
    protected $fillable = [
        'nama', 'genre','sutradara', 'tgl_rilis'
    ];
}

app/Http/Controllers/filmController.php
<?php

namespace App\Http\Controllers;

use App\Models\film;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class filmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    function __construct()
    {
        $this->middleware('role_or_permission:Film access|Film create|Film edit|Film delete', ['only' => ['index','show']]);
        $this->middleware('role_or_permission:Film create', ['only' => ['create','store']]);
        $this->middleware('role_or_permission:Film edit', ['only' => ['edit','update']]);
        $this->middleware('role_or_permission:Film delete', ['only' => ['destroy']]);
    }
    public function index()
    {
        $data = film::latest()->paginate(5);

        return view('films.index',compact('data'))
           ->with('cri', (request()->input('page', 1) - 1) * 5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('films.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'genre' => 'required',
            'tgl_rilis' => 'required',
            'sutradara' => 'required',
        ]);

        film::create($request->all());

        return redirect()->route('films.index')
                        ->with('success','film created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\film  $film
     * @return \Illuminate\Http\Response
     */
    public function show(film $film)
    {
        return view('films.show',compact('film'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\film  $film
     * @return \Illuminate\Http\Response
     */
    public function edit(film $film)
    {
        return view('films.edit',compact('film'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\film  $film
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, film $film)
    {
        $request->validate([
            'nama' => 'required',
            'genre' => 'required',
            'tgl_rilis' => 'required',
            'sutradara' => 'required',
        ]);

        $film->update($request->all());

        return redirect()->route('films.index')
                        ->with('success','film updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\film  $film
     * @return \Illuminate\Http\Response
     */
    public function destroy(film $film)
    {
        $film->delete();

        return redirect()->route('films.index')
                        ->with('success','film deleted successfully');
    }
    public function cri(Request $request)
    {
        // menangkap data pencarian
        $cri = $request->cri;

        // mengambil data dari table guru sesuai pencarian data
        $data = DB::table('films')
            ->where('nama','like',"%".$cri."%")
            ->paginate();


        // mengirim data pegawai ke view index
        return view('films.index',['data' => $data]);
    }


    // public function cari(Request $request)
    // {
    //     $mhsw = DB::table('value')
    //     ->where('mhsw.index','like',"%".$cari."%")
	// 	->paginate();

    //     return view('mhsws.index',['mhsw' => $mhsw]);
    // }
    // public function search(Request $request)
    // {
    //     $keyword = $request->search;
    //     $mhsw = mhsw::where('nama', 'like', "%" . $keyword . "%")->paginate(5);
    //     return view('mhsws.index', compact('mhsw'))->with('i', (request()->input('page', 1) - 1) * 5);
    // }
}

resources/views/films/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Tambah</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-danger" href="{{ route('films.index') }}"> Kembali</a>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('films.store') }}" method="POST">
            @csrf
          
             <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nama:</strong>
                        <input type="text" name="nama" class="form-control" placeholder="Masukkan nama">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Genre:</strong>
                        <input type="text" name="genre" class="form-control" placeholder="Masukkan Genre">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Tanggal Rilis:</strong>
                        <input type="date" name="tgl_rilis" class="form-control">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Sutradara:</strong>
                        <input type="text" name="sutradara" class="form-control" placeholder="Masukkan Nama Sutradara">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </div>
           
        </form>
    </div>
</div>
   
@endsection

resources/views/films/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Edit</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('films.index') }}"> Kembali</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <form action="{{ route('films.update',$film->id) }}" method="POST">
                @csrf
                @method('PUT')
            
                 <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Nama:</strong>
                            <input type="text" name="nama" value="{{ $film->nama }}" class="form-control" placeholder="Nama">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Genre:</strong>
                        <input type="text" name="genre" value="{{ $film->genre }}" class="form-control" placeholder="Genre">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Tanggal Rilis:</strong>
                        <input type="date" name="tgl_rilis" value="{{ $film->tgl_rilis }}" class="form-control">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Sutradara:</strong>
                        <input type="text" name="sutradara" value="{{ $film->sutradara }}" class="form-control" placeholder="Sutradara">
                    </div>
                </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/films/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h2 style="font: bold">DAFTAR FILM</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-8">
                    <div class="pull-left">
                    <a class="btn btn-success mb-2" href="{{ route('films.create') }}"> Tambah</a>
                    </div>
                    <div class="pull-right ">
                    </div>
            </div>
            <div class="col-md-4">
                    <form action={{ route('films.cri') }} method="GET">
                        <label>
                            <input type="text" name="cri">
                        </label>
                        <input type="submit" value="CARI">
                    </form> 
            </div>
        </div>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        
        <table class="table table-bordered">
            <tr>
                <th>Nama</th>
                <th>Genre</th>
                <th>Tanggal Rilis</th>
                <th>Sutradara</th>
                <th width="250px">Action</th>
            </tr>
            @foreach ($data as $key => $value)
                <tr>
                <td>{{ $value->nama }}</td>
                <td>{{ $value->genre}}</td>
                <td>{{ $value->tgl_rilis }}</td>
                <td>{{ $value->sutradara }}</td>
                <td>
                    <form action="{{ route('films.destroy',$value->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('films.show',$value->id) }}">Lihat</a>
                        <a class="btn btn-primary" href="{{ route('films.edit',$value->id) }}">Edit</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Hapus</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </table>
    </div>
</div>




        {{ $data->links() }}
    </div>

@endsection

resources/views/films/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="float-sm-left">
                        <h2> Tampilkan</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('films.index') }}"> Kembali</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nama:</strong>
                        {{ $film->nama }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Genre:</strong>
                        {{ $film->genre }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Tanggal Rilis:</strong>
                        {{ $film->tgl_rilis }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Sutradara:</strong>
                        {{ $film->sutradara }}
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection